### ISSUE TITLE
Does this only work with Naughty Dog games?

### ISSUE THREAD

**Issue by khangly** [bucanero/naughtydog-ps3save-decrypter#1]
As the tile, does this work with other PS3 games or just Naughty Dog games?

Edit: I tried with Oblivion and got `Segmentation fault`

**Comment by bucanero** [comment]
this tool is only meant to handle an additional custom encryption layer present in some Naughty Dog PS3 games (uncharted 2, uncharted 3, the last of us)

if you want to decrypt the generic encryption layer managed by the PS3 system, you should use a tool like [Apollo Save tool](https://github.com/bucanero/apollo-ps3) (runs directly on the PS3) or Bruteforce save data (runs on Windows).

**Comment by khangly** [comment]
Thanks!
